
#ifndef JAEGERNET_EXPORT_H
#define JAEGERNET_EXPORT_H

#ifdef SHARED_EXPORTS_BUILT_AS_STATIC
#  define JAEGERNET_EXPORT
#  define JAEGERNETSERVER_NO_EXPORT
#else
#  ifndef JAEGERNET_EXPORT
#    ifdef JaegerNetServer_EXPORTS
        /* We are building this library */
#      define JAEGERNET_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define JAEGERNET_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef JAEGERNETSERVER_NO_EXPORT
#    define JAEGERNETSERVER_NO_EXPORT 
#  endif
#endif

#ifndef JAEGERNETSERVER_DEPRECATED
#  define JAEGERNETSERVER_DEPRECATED __declspec(deprecated)
#endif

#ifndef JAEGERNETSERVER_DEPRECATED_EXPORT
#  define JAEGERNETSERVER_DEPRECATED_EXPORT JAEGERNET_EXPORT JAEGERNETSERVER_DEPRECATED
#endif

#ifndef JAEGERNETSERVER_DEPRECATED_NO_EXPORT
#  define JAEGERNETSERVER_DEPRECATED_NO_EXPORT JAEGERNETSERVER_NO_EXPORT JAEGERNETSERVER_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef JAEGERNETSERVER_NO_DEPRECATED
#    define JAEGERNETSERVER_NO_DEPRECATED
#  endif
#endif

#endif
